### ISSUE TITLE
Silk screen for Analog Supply and DAC Supply is incorrectly labeled

### ISSUE THREAD

**Issue by jalcok1** [marionette-daq/marionette-hardware#6]
Both silkscreens indicate that one pin is vref_in when it is actually 3.3V.  The other pin says its 3.3V and it is actually vref_in.

**Comment by jalcok1** [comment]
Correction, the silk screen for the analog supply is the only one that is incorrect.

**Comment by jalcok1** [comment]
Even better ….. The silkscreen for DAC and Analog Vref should be just removed.  The connectors J7 and J4 don't really serve a purpose.

**Comment by andrewgreenberg** [comment]
Fixed in v2.
